/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CategoryTitleLazyImport = createFileRoute('/$category/$title')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CategoryTitleLazyRoute = CategoryTitleLazyImport.update({
  id: '/$category/$title',
  path: '/$category/$title',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$category/$title.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$category/$title': {
      id: '/$category/$title'
      path: '/$category/$title'
      fullPath: '/$category/$title'
      preLoaderRoute: typeof CategoryTitleLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$category/$title': typeof CategoryTitleLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$category/$title': typeof CategoryTitleLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$category/$title': typeof CategoryTitleLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category/$title'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$category/$title'
  id: '__root__' | '/' | '/$category/$title'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryTitleLazyRoute: typeof CategoryTitleLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryTitleLazyRoute: CategoryTitleLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/$category/$title"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/$category/$title": {
      "filePath": "$category/$title.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
